version: '3.8'

services:
  mysql_db:
    image: mysql:8.0.41
    container_name: mysql_uat
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: placement
    ports:
      - "3307:3306"
    volumes:
      - mysql_uat_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_uat
    restart: always
    depends_on:
      - mysql_db
    environment:
      PMA_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8082:80"

  sikho-app:
    image: shafaiz/sikho-app:uat
    container_name: sikho_uat
    restart: always
    depends_on:
      - mysql_db
      - mailpit
    ports:
      - "9001:9000"
    environment:
      APP_ENV: uat
      DB_HOST: mysql_db
      DB_DATABASE: placement
      DB_USERNAME: root
      DB_PASSWORD: root
    volumes:
      - .:/app
    working_dir: /app
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=9000"]

  mailpit:
    image: axllent/mailpit
    container_name: mailpit_uat
    restart: always
    ports:
      - "8027:8025"
      - "1026:1025"

volumes:
  mysql_uat_data:

