version: '3.8'

services:
  mysql_db:
    image: mysql:8.0.41
    container_name: mysql_local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: placement
    ports:
      - "3306:3306"
    volumes:
      - mysql_local_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_local
    restart: always
    depends_on:
      - mysql_db
    environment:
      PMA_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"

  sikho-app:
    image: shafaiz/sikho-app:latest
    container_name: sikho_local
    restart: always
    depends_on:
      - mysql_db
      - mailpit
    ports:
      - "9000:9000"
    environment:
      APP_ENV: local
      DB_HOST: mysql_db
      DB_DATABASE: placement
      DB_USERNAME: root
      DB_PASSWORD: root
    volumes:
      - .:/app
    working_dir: /app
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=9000"]

  mailpit:
    image: axllent/mailpit
    container_name: mailpit_local
    restart: always
    ports:
      - "8026:8025"
      - "1025:1025"

volumes:
  mysql_local_data:

