global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'app'
    static_configs:
      - targets: ['192.168.5.164:9000']

  - job_name: 'mysql'
    static_configs:
      - targets: ['192.168.5.164:9104']

  - job_name: 'nginx'
    static_configs:
      - targets: ['192.168.5.164:9113']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.5.164:9090']
