apiVersion: v1
kind: Namespace
metadata:
  name: placement
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-config
  namespace: placement
data:
  sikho-app.conf: |
    <VirtualHost *:9000>
        ServerAdmin admin@sikho.com
        DocumentRoot /var/www/sikho-app/public

        <Directory /var/www/sikho-app/public>
            AllowOverride All
            Require all granted
        </Directory>

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
    </VirtualHost>
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sikho-app-pvc
  namespace: placement
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sikho-app
  namespace: placement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sikho-app
  template:
    metadata:
      labels:
        app: sikho-app
    spec:
      containers:
      - name: sikho-app
        image: shafaiz/sikho-app:latest
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: app-storage
          mountPath: /var/www/sikho-app
        - name: apache-config
          mountPath: /etc/apache2/sites-available/sikho-app.conf
          subPath: sikho-app.conf
        command: ["/bin/sh", "-c"]
        args:
          - |
            cp -r /var/www/html/* /var/www/sikho-app/ &&
            chown -R www-data:www-data /var/www/sikho-app &&
            chmod -R 775 /var/www/sikho-app/storage /var/www/sikho-app/bootstrap/cache &&
            a2ensite sikho-app &&
            a2dissite 000-default &&
            apachectl -D FOREGROUND
      volumes:
      - name: app-storage
        persistentVolumeClaim:
          claimName: sikho-app-pvc
      - name: apache-config
        configMap:
          name: apache-config
---
apiVersion: v1
kind: Service
metadata:
  name: sikho-app
  namespace: placement
spec:
  selector:
    app: sikho-app
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  namespace: placement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "sikho"
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-db
  namespace: placement
spec:
  selector:
    app: mysql-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: placement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        env:
        - name: PMA_HOST
          value: "mysql-db"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: placement
spec:
  selector:
    app: phpmyadmin
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailpit
  namespace: placement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailpit
  template:
    metadata:
      labels:
        app: mailpit
    spec:
      containers:
      - name: mailpit
        image: axllent/mailpit
        ports:
        - containerPort: 1025  # SMTP port
        - containerPort: 8025  # Web UI port
---
apiVersion: v1
kind: Service
metadata:
  name: mailpit
  namespace: placement
spec:
  selector:
    app: mailpit
  type: NodePort
  ports:
    - name: smtp
      protocol: TCP
      port: 1025
      targetPort: 1025
    - name: web
      protocol: TCP
      port: 8025
      targetPort: 8025
      nodePort: 30025

